/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Message;

import Client.Client;
import static Message.FirstPage.mainP;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.file.Files;
import java.util.ArrayList;
import static java.util.Collections.list;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author MERVE
 */
public class MainPage extends javax.swing.JFrame {
    public DefaultListModel dlm = new DefaultListModel();   // to holding clients
    public DefaultListModel dlm2 = new DefaultListModel();  // to holding rooms
    public Room rooms = new Room();
      public static ArrayList<Room> chat_rooms;
        HashMap<String, String> myPrivateChats = new HashMap<String, String>();
        //Ozel mesaj atmak icin listeden anlik kisi
    public String selectedUserForPrvChat = "";

    /**
     * Creates new form MainPage
     */
    public static FirstPage login = new FirstPage();
    public MainPage() {
        
        initComponents();
     //   list.setModel(dlm);
        roomList.setModel(dlm2);
        chat_rooms = new ArrayList<>();
    }
    
    
    public void online_users(DefaultListModel dlm) {
        // online olan kullanıcıların listelenmesi   
        String selected = my_user_list.getSelectedValue();
        my_user_list.setModel(dlm);
        boolean isChanged = true;
        if (selected != null) {
            for (int i = 0; i < dlm.size(); i++) {
                String uname = (String) dlm.get(i);

                if (selected.equals(uname)) {
                    my_user_list.setSelectedIndex(i);  //Liste güncellenirken,sohbet edilen kişi online ise set eder
                    isChanged = false;
                    break;
                }
            }
        }
        if (isChanged) {
            //Liste güncellerinirken, mesajlaşılan kişi offline olursa listedeki ilk kişi set olur
            my_user_list.setSelectedIndex(0);
        }
        
        new_priv_chat(dlm); //priv chat fonksiyonu çağılılır
       
    }
    

       public void new_priv_chat(DefaultListModel dlm) {
        //eğer yeni biri geldirse, içi boş sohbet olustur
        String username = (String) dlm.get(dlm.getSize() - 1);
        if (!myPrivateChats.containsKey(username)) {
            myPrivateChats.put(username, "");
        }

    }
        public void priv_rec_msg(PrivateMsg pmsg) {
      
       
        String oldMsgs = "";
        if (myPrivateChats.get(pmsg.getSender()) != null) { //gelen mesajım null değilse eğer
            oldMsgs = myPrivateChats.get(pmsg.getSender()); //sohbete yazılır
        }
   // seçilen kişiyle sohbette dlm güncelle
        myPrivateChats.put(pmsg.getSender(), oldMsgs + pmsg.getSender() + ": " + pmsg.getContent() + "\n");
        if (pmsg.getSender().equals(my_user_list.getSelectedValue())) {
            prive_screen.setText(myPrivateChats.get(pmsg.getSender()));
        }

    }
        




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        my_user_list = new javax.swing.JList<>();
        txt_priv = new javax.swing.JTextField();
        prive_screen = new java.awt.TextArea();
        btn_send_private = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        roomList = new javax.swing.JList<>();
        createTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        create = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        chat_screen = new java.awt.TextArea();
        send_btn = new javax.swing.JButton();
        send_file = new javax.swing.JButton();
        my_rooms = new javax.swing.JButton();
        chat_msg = new javax.swing.JTextField();
        join = new javax.swing.JButton();
        left_btn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(213, 177, 250));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setText("online users");

        my_user_list.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                my_user_listValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(my_user_list);

        txt_priv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_privActionPerformed(evt);
            }
        });

        prive_screen.setBackground(new java.awt.Color(255, 232, 255));
        prive_screen.setEditable(false);
        prive_screen.setForeground(new java.awt.Color(0, 0, 0));

        btn_send_private.setText("send priv");
        btn_send_private.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_send_privateActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel5.setText("Rooms");

        jScrollPane3.setViewportView(roomList);

        createTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createTxtActionPerformed(evt);
            }
        });

        jLabel6.setText("Enter New Room Name");

        create.setText("create");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Hi");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Chat");

        chat_screen.setBackground(new java.awt.Color(255, 232, 255));
        chat_screen.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        chat_screen.setEditable(false);

        send_btn.setText("send");
        send_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_btnActionPerformed(evt);
            }
        });

        send_file.setText("send file ");
        send_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_fileActionPerformed(evt);
            }
        });

        my_rooms.setText("rooms");
        my_rooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                my_roomsActionPerformed(evt);
            }
        });

        chat_msg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chat_msgActionPerformed(evt);
            }
        });

        join.setText("join room");
        join.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinActionPerformed(evt);
            }
        });

        left_btn.setText("Disconnect");
        left_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                left_btnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel7.setText("Private Chat");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chat_screen, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chat_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(send_file)
                                    .addComponent(send_btn))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(84, 84, 84)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(createTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(create, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(my_rooms)
                                            .addComponent(join, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jLabel5))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(71, 71, 71)
                                        .addComponent(prive_screen, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addComponent(txt_priv, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_send_private)))
                                .addContainerGap(39, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(left_btn)
                                .addGap(17, 17, 17))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(243, 243, 243)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(288, 288, 288)
                                .addComponent(jLabel6)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(left_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(1, 1, 1)
                        .addComponent(prive_screen, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_priv)
                            .addComponent(btn_send_private, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chat_screen, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chat_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(send_btn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(send_file)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(my_rooms)
                        .addGap(18, 18, 18)
                        .addComponent(join)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(createTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(create))
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chat_msgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chat_msgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chat_msgActionPerformed

    private void send_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_btnActionPerformed
        // TODO add your handling code here:
      
        Message msg = new Message(Message.Message_Type.Text);
        String x =jLabel4.getText() + ": " + chat_msg.getText();
        msg.content = x;
        Client.Send(msg);
        chat_msg.setText("");
        
       
    
        
    }//GEN-LAST:event_send_btnActionPerformed

    private void my_roomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_my_roomsActionPerformed
        Message msg = new Message(Message.Message_Type.room_list);
        Client.Send(msg);
    }//GEN-LAST:event_my_roomsActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        if (createTxt.getText().equals(null) || createTxt.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter a room name before creation !!");
            return;
        }
        Message msg = new Message(Message.Message_Type.room_name);
        msg.content = createTxt.getText();
        createTxt.setText("");
        Client.Send(msg);
    }//GEN-LAST:event_createActionPerformed

    private void joinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinActionPerformed
        Message msg = new Message(Message.Message_Type.room_join);
  
        msg.content = (String) roomList.getSelectedValue();
        System.out.println("choosen room name: "+msg.content);
        
             ArrayList<String> cnt=new ArrayList<>();
             
             cnt.add(roomList.getSelectedValue());
            
             cnt.add(jLabel4.toString());
             
             rooms.lbl_roomName.setText(roomList.getSelectedValue()+"");
         
             msg.content=cnt;
            Client.Send(msg);
          
            rooms.setVisible(true);
       
    }//GEN-LAST:event_joinActionPerformed

    private void txt_privActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_privActionPerformed
      
    }//GEN-LAST:event_txt_privActionPerformed

    private void btn_send_privateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_send_privateActionPerformed
      
        // Server uzerinden, listeden secilen kullaniciya, ozel mesaj gonderir
        // prive_msg nesnesi
        String senderUsername = jLabel4.getText();
        String targetUsername = my_user_list.getSelectedValue();
        String content = txt_priv.getText();
        PrivateMsg pmsg = new PrivateMsg(senderUsername, targetUsername, content);
        String oldMsgs = "";
        if (myPrivateChats.get(pmsg.getTarget()) != null) {
            oldMsgs = myPrivateChats.get(targetUsername);
        }

        myPrivateChats.put(targetUsername, oldMsgs + senderUsername + ": " + content + "\n");
        prive_screen.setText(myPrivateChats.get(targetUsername));
        txt_priv.setText("");

        Message msg = new Message(Message.Message_Type.prive_msg);
        msg.content = pmsg;
        Client.Send(msg);

    }//GEN-LAST:event_btn_send_privateActionPerformed

    private void send_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_fileActionPerformed

/*** file kısmını internetten araştırıp bularak yatim**/

        JFileChooser fileChooser = new JFileChooser();
        int selection = fileChooser.showOpenDialog(this);

        File file = null;
        // keep selected file from chooser in file variable
        if (selection == JFileChooser.APPROVE_OPTION)
        file = fileChooser.getSelectedFile();

        byte fileContent[] = new byte[(int)file.length()];
        try {
            BufferedInputStream bis = new BufferedInputStream(new FileInputStream(file));
            bis.read(fileContent, 0, fileContent.length);
            Message fileMSG = new Message(Message.Message_Type.File_t);
            fileMSG.file_cont = fileContent;
            fileMSG.content = file.getName(); // msg.content == file name
            Client.Send(fileMSG);
            System.out.println("File path : "+file.getAbsolutePath());
 // notifying to message sended by who
          String file_send =  jLabel4.getText();
 
            Message notifyFileMSG = new Message(Message.Message_Type.File_Notify);
            notifyFileMSG.content = file_send.toUpperCase() + ": " + file.getName() + " shared";
            Client.Send(notifyFileMSG);

        } catch (FileNotFoundException ex) {
            System.out.println("File dont found! "+ex);
        } catch (IOException ex) {
            System.out.println("File read exception'"+ex);
        }
        
    }//GEN-LAST:event_send_fileActionPerformed

    private void createTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createTxtActionPerformed
       
    }//GEN-LAST:event_createTxtActionPerformed

    private void left_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_left_btnActionPerformed
      
                if (chat_rooms.size() == 0) {
                        Message msg = new Message(Message.Message_Type.Leaving);
                        String x = jLabel4.getText();
                        msg.content = x;
                        Client.Send(msg);
            
                        Client.Stop();
                        FirstPage.mainP.setVisible(false);

                    }
    }//GEN-LAST:event_left_btnActionPerformed

    private void my_user_listValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_my_user_listValueChanged
        // TODO add your handling code here:
          selectedUserForPrvChat = my_user_list.getSelectedValue();
        if (selectedUserForPrvChat != null && selectedUserForPrvChat.equals(jLabel4.getText())) {
            prive_screen.setText("");
            prive_screen.setEnabled(false);
            prive_screen.setEnabled(false);
            btn_send_private.setEnabled(false);
        } else {
            prive_screen.setText(myPrivateChats.get(selectedUserForPrvChat));
            prive_screen.setEnabled(true);
            txt_priv.setEnabled(true);
            btn_send_private.setEnabled(true);

        }

        
        
    }//GEN-LAST:event_my_user_listValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_send_private;
    private javax.swing.JTextField chat_msg;
    public java.awt.TextArea chat_screen;
    public javax.swing.JButton create;
    public javax.swing.JTextField createTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JButton join;
    private javax.swing.JButton left_btn;
    public javax.swing.JButton my_rooms;
    private javax.swing.JList<String> my_user_list;
    public java.awt.TextArea prive_screen;
    public javax.swing.JList<String> roomList;
    private javax.swing.JButton send_btn;
    public javax.swing.JButton send_file;
    private javax.swing.JTextField txt_priv;
    // End of variables declaration//GEN-END:variables
}
